# Generated by Django 3.1.3 on 2021-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='year',
        ),
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
